#pragma once
static const char* header_html = {
  "<!DOCTYPE HTML>\n"
  "<html>\n"
  "<head>\n"
  "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
  "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
  "    <title>YALC</title>\n"
  "    <style>\n"
  "        * {\n"
  "          box-sizing: border-box;\n"
  "        }\n"
  "\n"
  "        .menu {\n"
  "          float: left;\n"
  "          width: 20%;\n"
  "          text-align: center;\n"
  "        }\n"
  "\n"
  "        .menu a {\n"
  "          background-color: #e5e5e5;\n"
  "          padding: 8px;\n"
  "          margin-top: 7px;\n"
  "          display: block;\n"
  "          width: 100%;\n"
  "          color: black;\n"
  "        }\n"
  "\n"
  "        .main {\n"
  "          float: left;\n"
  "          width: 80%;\n"
  "          padding: 0 20px;\n"
  "        }\n"
  "\n"
  "        @media only screen and (max-width: 620px) {\n"
  "          /* For mobile phones: */\n"
  "          .menu, .main {\n"
  "            width: 100%;\n"
  "          }\n"
  "        }\n"
  "        </style>\n"
  "        </head>\n"
  "</head>\n"
  "\n"
  "<body>\n"
  "    <div style=\"background-color:#e5e5e5;padding:15px;text-align:center;\">\n"
  "        <h1>YALC</h1>\n"
  "      </div>\n"
  "\n"
  "      <div style=\"overflow:auto\">\n"
  "        <div class=\"menu\">\n"
  "          <a href=\"/connectionSettings\">Connection</a>\n"
  "          <a href=\"/effects\">Effects</a>\n"
  "          <a href=\"/leds\">Leds</a>\n"
  "          <a href=\"/reboot\">Reboot</a>\n"
  "        </div>\n"
  "\n"
  "        <div class=\"main\">"
};